// This file was generated by Conjure and should not be manually edited.

package api

import (
	"github.com/palantir/conjure-go-runtime/conjure-go-contract/errors"
	"github.com/palantir/pkg/binary"
	"github.com/palantir/pkg/boolean"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
	"github.com/palantir/pkg/uuid"
	"github.com/tidwall/gjson"
)

type Basic struct {
	Data string
}

func (o Basic) MarshalJSON() ([]byte, error) {
	type BasicAlias Basic
	return safejson.Marshal(BasicAlias(o))
}

func (o *Basic) UnmarshalJSON(data []byte) error {
	if !gjson.ValidBytes(data) {
		return errors.NewInvalidArgument()
	}
	value := gjson.ParseBytes(data)
	if !value.IsObject() {
		return errors.NewInvalidArgument()
	}
	var err error
	value.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "data":
			if value.Type != gjson.String {
				err = errors.NewInvalidArgument()
				return false
			}
			o.Data = value.Str
		}
		return err == nil
	})
	return err
}

func (o Basic) MarshalYAML() (interface{}, error) {
	jsonBytes, err := o.MarshalJSON()
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Basic) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return o.UnmarshalJSON(jsonBytes)
}

type BinaryMap struct {
	Map map[binary.Binary][]byte
}

func (o BinaryMap) MarshalJSON() ([]byte, error) {
	if o.Map == nil {
		o.Map = make(map[binary.Binary][]byte, 0)
	}
	type BinaryMapAlias BinaryMap
	return safejson.Marshal(BinaryMapAlias(o))
}

func (o *BinaryMap) UnmarshalJSON(data []byte) error {
	if !gjson.ValidBytes(data) {
		return errors.NewInvalidArgument()
	}
	value := gjson.ParseBytes(data)
	if !value.IsObject() {
		return errors.NewInvalidArgument()
	}
	var err error
	value.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "map":
			if !value.IsObject() {
				err = errors.NewInvalidArgument()
				return false
			}
			if o.Map == nil {
				o.Map = make(map[binary.Binary][]byte)
			}
			value.ForEach(func(key, value gjson.Result) bool {
				if key.Type != gjson.String {
					err = errors.NewInvalidArgument()
					return false
				}
				var destKey []byte
				destKey, err = binary.Binary(key.Str).Bytes()
				if value.Type != gjson.String {
					err = errors.NewInvalidArgument()
					return false
				}
				var destVal []byte
				destVal, err = binary.Binary(value.Str).Bytes()
				o.Map[destKey] = destVal
				return err == nil
			})
		}
		return err == nil
	})
	return err
}

func (o BinaryMap) MarshalYAML() (interface{}, error) {
	jsonBytes, err := o.MarshalJSON()
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *BinaryMap) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return o.UnmarshalJSON(jsonBytes)
}

type BooleanIntegerMap struct {
	Map map[boolean.Boolean]int
}

func (o BooleanIntegerMap) MarshalJSON() ([]byte, error) {
	if o.Map == nil {
		o.Map = make(map[boolean.Boolean]int, 0)
	}
	type BooleanIntegerMapAlias BooleanIntegerMap
	return safejson.Marshal(BooleanIntegerMapAlias(o))
}

func (o *BooleanIntegerMap) UnmarshalJSON(data []byte) error {
	if !gjson.ValidBytes(data) {
		return errors.NewInvalidArgument()
	}
	value := gjson.ParseBytes(data)
	if !value.IsObject() {
		return errors.NewInvalidArgument()
	}
	var err error
	value.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "map":
			if !value.IsObject() {
				err = errors.NewInvalidArgument()
				return false
			}
			if o.Map == nil {
				o.Map = make(map[boolean.Boolean]int)
			}
			value.ForEach(func(key, value gjson.Result) bool {
				if key.Type != gjson.False && key.Type != gjson.True {
					err = errors.NewInvalidArgument()
					return false
				}
				var destKey bool
				destKey = key.Bool
				if value.Type != gjson.Number {
					err = errors.NewInvalidArgument()
					return false
				}
				var destVal int
				destVal = int(value.Int())
				o.Map[destKey] = destVal
				return err == nil
			})
		}
		return err == nil
	})
	return err
}

func (o BooleanIntegerMap) MarshalYAML() (interface{}, error) {
	jsonBytes, err := o.MarshalJSON()
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *BooleanIntegerMap) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return o.UnmarshalJSON(jsonBytes)
}

type Collections struct {
	MapVar   map[string][]int
	ListVar  []string
	MultiDim [][]map[string]int
}

func (o Collections) MarshalJSON() ([]byte, error) {
	if o.MapVar == nil {
		o.MapVar = make(map[string][]int, 0)
	}
	if o.ListVar == nil {
		o.ListVar = make([]string, 0)
	}
	if o.MultiDim == nil {
		o.MultiDim = make([][]map[string]int, 0)
	}
	type CollectionsAlias Collections
	return safejson.Marshal(CollectionsAlias(o))
}

func (o *Collections) UnmarshalJSON(data []byte) error {
	if !gjson.ValidBytes(data) {
		return errors.NewInvalidArgument()
	}
	value := gjson.ParseBytes(data)
	if !value.IsObject() {
		return errors.NewInvalidArgument()
	}
	var err error
	value.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "mapVar":
			if !value.IsObject() {
				err = errors.NewInvalidArgument()
				return false
			}
			if o.MapVar == nil {
				o.MapVar = make(map[string][]int)
			}
			value.ForEach(func(key, value gjson.Result) bool {
				if key.Type != gjson.String {
					err = errors.NewInvalidArgument()
					return false
				}
				var destKey string
				destKey = key.Str
				var destVal []int
				if !value.IsArray() {
					err = errors.NewInvalidArgument()
					return false
				}
				value.ForEach(func(_, value gjson.Result) bool {
					if value.Type != gjson.Number {
						err = errors.NewInvalidArgument()
						return false
					}
					var v int
					v = int(value.Int())
					destVal = append(destVal, v)
					return err == nil
				})
				o.MapVar[destKey] = destVal
				return err == nil
			})
		case "listVar":
			if !value.IsArray() {
				err = errors.NewInvalidArgument()
				return false
			}
			value.ForEach(func(_, value gjson.Result) bool {
				if value.Type != gjson.String {
					err = errors.NewInvalidArgument()
					return false
				}
				var v string
				v = value.Str
				o.ListVar = append(o.ListVar, v)
				return err == nil
			})
		case "multiDim":
			if !value.IsArray() {
				err = errors.NewInvalidArgument()
				return false
			}
			value.ForEach(func(_, value gjson.Result) bool {
				var v []map[string]int
				if !value.IsArray() {
					err = errors.NewInvalidArgument()
					return false
				}
				value.ForEach(func(_, value gjson.Result) bool {
					var v map[string]int
					if !value.IsObject() {
						err = errors.NewInvalidArgument()
						return false
					}
					if v == nil {
						v = make(map[string]int)
					}
					value.ForEach(func(key, value gjson.Result) bool {
						if key.Type != gjson.String {
							err = errors.NewInvalidArgument()
							return false
						}
						var destKey string
						destKey = key.Str
						if value.Type != gjson.Number {
							err = errors.NewInvalidArgument()
							return false
						}
						var destVal int
						destVal = int(value.Int())
						v[destKey] = destVal
						return err == nil
					})
					v = append(v, v)
					return err == nil
				})
				o.MultiDim = append(o.MultiDim, v)
				return err == nil
			})
		}
		return err == nil
	})
	return err
}

func (o Collections) MarshalYAML() (interface{}, error) {
	jsonBytes, err := o.MarshalJSON()
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Collections) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return o.UnmarshalJSON(jsonBytes)
}

type Compound struct {
	Obj Collections
}

func (o Compound) MarshalJSON() ([]byte, error) {
	type CompoundAlias Compound
	return safejson.Marshal(CompoundAlias(o))
}

func (o *Compound) UnmarshalJSON(data []byte) error {
	if !gjson.ValidBytes(data) {
		return errors.NewInvalidArgument()
	}
	value := gjson.ParseBytes(data)
	if !value.IsObject() {
		return errors.NewInvalidArgument()
	}
	var err error
	value.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "obj":
			err = o.Obj.UnmarshalJSON([]byte(value.Raw))
		}
		return err == nil
	})
	return err
}

func (o Compound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := o.MarshalJSON()
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Compound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return o.UnmarshalJSON(jsonBytes)
}

type ExampleUuid struct {
	Uid uuid.UUID
}

func (o ExampleUuid) MarshalJSON() ([]byte, error) {
	type ExampleUuidAlias ExampleUuid
	return safejson.Marshal(ExampleUuidAlias(o))
}

func (o *ExampleUuid) UnmarshalJSON(data []byte) error {
	if !gjson.ValidBytes(data) {
		return errors.NewInvalidArgument()
	}
	value := gjson.ParseBytes(data)
	if !value.IsObject() {
		return errors.NewInvalidArgument()
	}
	var err error
	value.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "uid":
			if value.Type != gjson.String {
				err = errors.NewInvalidArgument()
				return false
			}
			err = o.Uid.UnmarshalText([]byte(value.Str))
		}
		return err == nil
	})
	return err
}

func (o ExampleUuid) MarshalYAML() (interface{}, error) {
	jsonBytes, err := o.MarshalJSON()
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ExampleUuid) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return o.UnmarshalJSON(jsonBytes)
}

// A type using go keywords
type Type struct {
	Type []string
	Chan map[string]string
}

func (o Type) MarshalJSON() ([]byte, error) {
	if o.Type == nil {
		o.Type = make([]string, 0)
	}
	if o.Chan == nil {
		o.Chan = make(map[string]string, 0)
	}
	type TypeAlias Type
	return safejson.Marshal(TypeAlias(o))
}

func (o *Type) UnmarshalJSON(data []byte) error {
	if !gjson.ValidBytes(data) {
		return errors.NewInvalidArgument()
	}
	value := gjson.ParseBytes(data)
	if !value.IsObject() {
		return errors.NewInvalidArgument()
	}
	var err error
	value.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "type":
			if !value.IsArray() {
				err = errors.NewInvalidArgument()
				return false
			}
			value.ForEach(func(_, value gjson.Result) bool {
				if value.Type != gjson.String {
					err = errors.NewInvalidArgument()
					return false
				}
				var v string
				v = value.Str
				o.Type = append(o.Type, v)
				return err == nil
			})
		case "chan":
			if !value.IsObject() {
				err = errors.NewInvalidArgument()
				return false
			}
			if o.Chan == nil {
				o.Chan = make(map[string]string)
			}
			value.ForEach(func(key, value gjson.Result) bool {
				if key.Type != gjson.String {
					err = errors.NewInvalidArgument()
					return false
				}
				var destKey string
				destKey = key.Str
				if value.Type != gjson.String {
					err = errors.NewInvalidArgument()
					return false
				}
				var destVal string
				destVal = value.Str
				o.Chan[destKey] = destVal
				return err == nil
			})
		}
		return err == nil
	})
	return err
}

func (o Type) MarshalYAML() (interface{}, error) {
	jsonBytes, err := o.MarshalJSON()
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Type) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return o.UnmarshalJSON(jsonBytes)
}
